### PR TITLE
Add comment support in testfairyConfig

### PR DESCRIPTION
**Pull request by IonutGavris**
Use it like this:

```
testfairyConfig {
    comment "Your build comment."
}
```

or add comments from a txt file:

```
testfairyConfig {
    commentFilePath "release_notes.txt"
}
```

https://github.com/testfairy/testfairy-gradle-plugin/issues/1
https://github.com/testfairy/testfairy-gradle-plugin/issues/9

### CODE REVIEW

**Comment by IonutGavris** [comment]
?

**Comment by 4eRTuk** [comment]
@gmegidish @tishma @testfairy Could you accept PR and update plugin please? I would be appreciate!

**Comment by casz** [comment]
@testfairy any chance of this being merged?

**Comment by casz** [comment]
For now I actually found a workaround 👍
This is based on being run on Jenkins

```
def testFairyAPI = System.getenv('TESTFAIRYKEY') ?: "0"
def build_Number = System.getenv('BUILD_NUMBER') ?: "0"

def getChangeLog() {
    def since = System.getenv('GIT_PREVIOUS_SUCCESSFUL_COMMIT') ?: "HEAD^^^^^"
    def stdout = new ByteArrayOutputStream()
    exec {
        commandLine 'git', 'log', "--pretty=format:- (%ae) %s", "${since}..head"
        standardOutput = stdout
    }
    return stdout
            .toString()
            .trim()
            .replaceAll("(?m)^.*(Merge pull request|Merge branch).*(?:\\r?\\n)?",
            "") ?: "No changes"
}

project.ext["testfairyChangelog"] = "Build ${build_Number}\n${getChangeLog()}"
```

**Comment by gmegidish** [comment]
Thanks everybody for their comments. So much time has passed, and so many has changed. I hope our changes to the plugin address your patches. I'm closing this pull request in our attempt to reach zero pull requests. Again, thank you for everything!

**Pull request closed without merging**
